name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4  # 关键步骤：设置 pnpm
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm  # 缓存 pnpm 依赖
          
      - name: 安装依赖
        run: pnpm install --frozen-lockfile  # 使用 pnpm
        
      - name: 构建项目
        run: pnpm run build
        
      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
